# Generated by Django 5.2.8 on 2025-12-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completion_aggregator', '0005_cachegroupinvalidation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aggregator',
            new_name='completion__user_id_01f5df_idx',
            old_fields=('user', 'aggregation_name', 'course_key'),
        ),
        migrations.RenameIndex(
            model_name='aggregator',
            new_name='completion__course__b3b80b_idx',
            old_fields=('course_key', 'aggregation_name', 'block_key', 'percent'),
        ),
        migrations.RenameIndex(
            model_name='stalecompletion',
            new_name='completion__usernam_36fa90_idx',
            old_fields=('username', 'course_key', 'created', 'resolved'),
        ),
    ]
